remoteUrl: http://127.0.0.1:9998/wd/hub
automation: UiAutomator2
platformz: android
platformVersion: '12'
deviceName: emulator-5556
udid: emulator-5556
systemPort: 8201
LANG: en
enforceXPath1: 60000
noReset: true
appPackage: com.ebay.mobile
appActivity: com.ebay.mobile.home.impl.main.MainActivity
require_farm: false


GLOBAL_TIMEOUT: 60