remoteUrl: http://127.0.0.1:4725/wd/hub
automation: UiAutomator2
platformz: android
platformVersion: '12'
deviceName: 26ab25c053217ece
udid: 26ab25c053217ece
systemPort: 18087
enforceXPath1: 60000
appPackage: com.ebay.mobile
appActivity: com.ebay.mobile.home.impl.main.MainActivity
require_farm: false


GLOBAL_TIMEOUT: 60